title: CSCI-UA.0480 Fall 2017, Section 008

baseurl: ""
resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../../resources/lib"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]

 
#book_node: "Node: Up and Running"
#book_node_link: http://chimera.labs.oreilly.com/books/1234000001808/index.html
#book_node_author: Tom Hughes-Croucher, Mike Wilson
#book_web: "Web Dev w/ Node & Express"
#book_web_link: http://shop.oreilly.com/product/0636920032977.do
#book_web_author: "Ethan Brown"

vars:
    book_js: "Speaking JavaScript"
    book_js_note: "(free to read online)"
    book_js_link: http://speakingjs.com/es5/index.html
    book_js_author: Axel Rauschmayer

    book_js_2: "Exploring ES6"
    book_js_2_note: "(free to read online)"
    book_js_2_link: http://exploringjs.com/es6/index.html 
    book_js_2_author: Axel Rauschmayer

    book_js_3: "You Don't Know JS"
    book_js_3_note: "(free to read online)"
    book_js_3_link: "https://github.com/getify/You-Dont-Know-JS/"
    book_js_3_author: Kyle Simpson

    book_js_4: "JavaScript Allongé, the \"Six\" Edition" 
    book_js_4_note: "(free to read online)"
    book_js_4_link: https://leanpub.com/javascriptallongesix/read 
    book_js_4_author: "Reg \"raganwald\" Braithwaite"

    book_js_5: Eloquent JavaScript, 2nd Edition
    book_js_5_note: "(free to read online)"
    book_js_5_link: http://eloquentjavascript.net/
    book_js_5_author: Marijn Haverbeke

    book_js_6: "Node: Up and Running"
    book_js_6_note: "(free to read online)"
    book_js_6_link: "http://chimera.labs.oreilly.com/books/1234000001808/index.html"
    book_js_6_author: Tom Hughes-Croucher and Mike Wilson

    book_js_7: "DOM Enlightenment"
    book_js_7_note: "(draft version free to read online)"
    book_js_7_link: "http://domenlightenment.com/"
    book_js_7_author: Cody Lindley 

    book_js_8: "Learning JavaScript Design Patterns"
    book_js_8_note: "(free to read online)"
    book_js_8_link: "https://addyosmani.com/resources/essentialjsdesignpatterns/book/"
    book_js_8_author: Addy Osmani 

    book_js_9: "Programming JavaScript Applications"
    book_js_9_note: "(free to read online)"
    book_js_9_link: "http://chimera.labs.oreilly.com/books/1234000000262/index.html"
    book_js_9_author: Eric Elliott 

    survey_intro: https://docs.google.com/forms/d/e/1FAIpQLScNVF3rD6QbIMNAclbz85Syq6T4JFONUmhRiA3UxfwXmB-QvQ/viewform
    piazza: https://piazza.com/nyu/spring2018/csciua0480section008

    email: jversoza@cs.nyu.edu
    contact_link: https://piazza.com/nyu/spring2018/csciua0480section008/home
    contact_label: piazza
    contact_note: (the best way to contact me!) 

    course_number: "CSCI-UA.0480"
    course_section: "008"
    course_name: "Applied Internet Technology"
    course_semester: "Spring 2018"
    course_time: "Mondays and Wednesdays, 11:00AM - 12:15PM"
    course_room: WWH 109
    course_site: http://foureyes.github.io/csci-ua.0480-spring2018-008/
    course_site_alt: http://cs.nyu.edu/~jversoza

    # office hours
    office_hours: "<br>&nbsp;12:45 - 2:15pm on Mondays and Tuesdays at WWH"
    office_hours_room: WWH 422 

    # finals
    # CSCI-UA.0480-002  Special Topics: Applied Internet Technology Joseph Versoza      Tuesday, December 16, 2014  8:00AM - 9:50AM 
    final_date: Dec 13
    final_day: Wed
    final_time: "3:30PM - 4:45PM"
    final_room: WWH 109
    survey_github: https://docs.google.com/forms/d/e/1FAIpQLScIwproK_ZLJTZ2jrRjbx1b7FnaYnXuvx6zCLORR4HrRiERtQ/viewform
    
    node_version: 9.x.x

    slides_img_prefix: "../../resources/img"


#book_js: "Speaking JavaScript"
#book_js_note: "(free to read online)"
#book_js_link: http://speakingjs.com/es5/index.html
#book_js_author: Axel Rauschmayer

#book_js_2: "Exploring ES6"
#book_js_2_note: "(free to read online)"
#book_js_2_link: http://exploringjs.com/es6/index.html 
#book_js_2_author: Axel Rauschmayer

#book_js_3: "You Don't Know JS"
#book_js_3_note: "(free to read online)"
#book_js_3_link: "https://github.com/getify/You-Dont-Know-JS/"
#book_js_3_author: Kyle Simpson

#book_js_4: "JavaScript Allongé, the \"Six\" Edition" 
#book_js_4_note: "(free to read online)"
#book_js_4_link: https://leanpub.com/javascriptallongesix/read 
#book_js_4_author: "Reg \"raganwald\" Braithwaite"

#book_js_5: Eloquent JavaScript, 2nd Edition
#book_js_5_note: "(free to read online)"
#book_js_5_link: http://eloquentjavascript.net/
#book_js_5_author: Marijn Haverbeke

#book_js_6: "Node: Up and Running"
#book_js_6_note: "(free to read online)"
#book_js_6_link: "http://chimera.labs.oreilly.com/books/1234000001808/index.html"
#book_js_6_author: Tom Hughes-Croucher and Mike Wilson

#book_js_7: "DOM Enlightenment"
#book_js_7_note: "(draft version free to read online)"
#book_js_7_link: "http://domenlightenment.com/"
#book_js_7_author: Cody Lindley 

#book_js_8: "Learning JavaScript Design Patterns"
#book_js_8_note: "(free to read online)"
#book_js_8_link: "https://addyosmani.com/resources/essentialjsdesignpatterns/book/"
#book_js_8_author: Addy Osmani 

#book_js_9: "Programming JavaScript Applications"
#book_js_9_note: "(free to read online)"
#book_js_9_link: "http://chimera.labs.oreilly.com/books/1234000000262/index.html"
#book_js_9_author: Eric Elliott 
